In [1]:
#importing required liberary
import numpy as np
import pandas as pd

In [2]:
#import datasets
data=pd.read_csv("dataset.csv");

In [3]:
#reading 5 dataset
data.head()

x1        x2        x3          y
0  2.173282  2.350076  2.415250  35.708201
1  5.555118  5.993455  3.045520  60.201730
2  4.799505  3.901152  4.451028  56.969898
3  2.581442  5.075955  4.103971  54.576365
4  1.241630  4.261207  4.567827  50.139696

In [4]:
#viewing size of dataset
data['x1'].size

1000

In [5]:
#Taking 70% of data as training set
k=(int)(0.7*data['x1'].size)
x1=np.array(data.loc[:k-1,'x1'])
x2=np.array(data.loc[:k-1,'x2'])
x3=np.array(data.loc[:k-1,'x3'])
y=np.array(data.loc[:k-1,'y'])

In [6]:
#checking Size of training set
len(x1)

700

In [7]:
#Taking rest 30% as test data
x1_test=np.array(data.loc[k:,'x1'])
x2_test=np.array(data.loc[k:,'x2'])
x3_test=np.array(data.loc[k:,'x3'])
y_test=np.array(data.loc[k:,'y'])

In [8]:
#linear regression model
x1x1=x1*x1
x1x1_mean=x1x1.mean()

In [9]:
x1x2=x1*x2
x1x2_mean=x1x2.mean()

In [10]:
x1x3=x1*x3
x1x3_mean=x1x3.mean()

In [11]:
x1_mean=x1.mean()

In [12]:
x1y=x1*y
x1y_mean=x1y.mean()

In [13]:
x2x2=x2*x2
x2x2_mean=x2x2.mean()

In [14]:
x2x3=x2*x3
x2x3_mean=x2x3.mean()

In [15]:
x2_mean=x2.mean()

In [16]:
x2y=x2*y
x2y_mean=x2y.mean()

In [17]:
x3x3=x3*x3
x3x3_mean=x3x3.mean()

In [18]:
x3_mean=x3.mean()

In [19]:
x3y=x3*y
x3y_mean=x3y.mean()

In [20]:
y_mean=y.mean()

In [21]:
#creating augmented matrix
M=np.array([[x1x1_mean, x1x2_mean, x1x3_mean, x1_mean,  x1y_mean],
            [x1x2_mean, x2x2_mean, x2x3_mean, x2_mean,  x2y_mean],
            [x1x3_mean, x2x3_mean, x3x3_mean, x3_mean,  x3y_mean],
            [x1_mean,   x2_mean,   x3_mean,   1.0,      y_mean]])
print(M)

[[ 14.38508219  12.42112691  12.16590634   3.4890837  174.3975606 ]
 [ 12.42112691  14.73470577  12.48005406   3.55463113 180.01908813]
 [ 12.16590634  12.48005406  14.25996736   3.50256204 179.07818219]
 [  3.4890837    3.55463113   3.50256204   1.          48.46222841]]


In [22]:
#performing row operation R3->R3-(M30/M00)R0
M[3,:]=M[3,:]-(M[3,0]/M[0,0])*M[0,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [1.24211269e+01 1.47347058e+01 1.24800541e+01 3.55463113e+00
  1.80019088e+02]
 [1.21659063e+01 1.24800541e+01 1.42599674e+01 3.50256204e+00
  1.79078182e+02]
 [0.00000000e+00 5.41902329e-01 5.51736664e-01 1.53727111e-01
  6.16231814e+00]]


In [23]:
#performing row operation R2->R2-(M20/M00)R0
M[2,:]=M[2,:]-(M[2,0]/M[0,0])*M[0,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [1.24211269e+01 1.47347058e+01 1.24800541e+01 3.55463113e+00
  1.80019088e+02]
 [0.00000000e+00 1.97512510e+00 3.97088628e+00 5.51736664e-01
  3.15848026e+01]
 [0.00000000e+00 5.41902329e-01 5.51736664e-01 1.53727111e-01
  6.16231814e+00]]


In [24]:
#performing row operation R1->R1-(M10/M00)R0
M[1,:]=M[1,:]-(M[1,0]/M[0,0])*M[0,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [0.00000000e+00 4.00940079e+00 1.97512510e+00 5.41902329e-01
  2.94315416e+01]
 [0.00000000e+00 1.97512510e+00 3.97088628e+00 5.51736664e-01
  3.15848026e+01]
 [0.00000000e+00 5.41902329e-01 5.51736664e-01 1.53727111e-01
  6.16231814e+00]]


In [25]:
#performing row operation R3->R3-(M31/M11)R1
M[3,:]=M[3,:]-(M[3,1]/M[1,1])*M[1,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [0.00000000e+00 4.00940079e+00 1.97512510e+00 5.41902329e-01
  2.94315416e+01]
 [0.00000000e+00 1.97512510e+00 3.97088628e+00 5.51736664e-01
  3.15848026e+01]
 [0.00000000e+00 0.00000000e+00 2.84782836e-01 8.04847119e-02
  2.18441176e+00]]


In [26]:
#performing row operation R2->R2-(M21/M11)*R1
M[2,:]=M[2,:]-(M[2,1]/M[1,1])*M[1,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [0.00000000e+00 4.00940079e+00 1.97512510e+00 5.41902329e-01
  2.94315416e+01]
 [0.00000000e+00 0.00000000e+00 2.99789322e+00 2.84782836e-01
  1.70861332e+01]
 [0.00000000e+00 0.00000000e+00 2.84782836e-01 8.04847119e-02
  2.18441176e+00]]


In [27]:
#performing row operation R3->R3-(M32/M22)R2
M[3,:]=M[3,:]-(M[3,2]/M[2,2])*M[2,:]
print(M)

[[1.43850822e+01 1.24211269e+01 1.21659063e+01 3.48908370e+00
  1.74397561e+02]
 [0.00000000e+00 4.00940079e+00 1.97512510e+00 5.41902329e-01
  2.94315416e+01]
 [0.00000000e+00 0.00000000e+00 2.99789322e+00 2.84782836e-01
  1.70861332e+01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.34319593e-02
  5.61326111e-01]]


In [28]:
#Calculating constant k=M34/M33
k=M[3,4]/M[3,3]
print(k)

10.505437541342411


In [29]:
#calculating cofficient a3=(M24-k*M23)/M22
a3=(M[2,4]-k*M[2,3])/M[2,2]
print(a3)

4.701423248278179


In [30]:
#calculating cofficient a2=(M14-(a3*M12+k*M13))/M11
a2=(M[1,4]-(a3*M[1,2]+k*M[1,3]))/M[1,1]
print(a2)

3.604708608107475


In [31]:
#calculating cofficient a1=(M04-()
a1=(M[0,4]-(a2*M[0,1]+a3*M[0,2]+k*M[0,3]))/M[0,0]
print(a1)

2.4867144508993757


In [32]:
#Learned Linear function
print("Y={}X1+{}X2+{}X3+{}".format(round(a1,2),round(a2,2),round(a3,2),round(k,2)))

Y=2.49X1+3.6X2+4.7X3+10.51


In [33]:
#predicting y
y_pred=a1*x1_test+a2*x2_test+a3*x3_test+k

In [34]:
mean_sq_error=((y_pred-y_test)**2).sum()/len(y_test)
print("mean square error",mean_sq_error)

mean square error 0.08354258244611353


In [35]:
#importing liberary for accuracy check
from sklearn.metrics import mean_squared_error, r2_score
print("Mean squaed error ",mean_squared_error(y_test,y_pred))
print("r2 score ",r2_score(y_test,y_pred))

Mean squaed error  0.08354258244611353
r2 score  0.9990598531287528
