In [0]:
import numpy as np
import pandas as pd

In [0]:
data = pd.read_csv("dataset.csv")

In [3]:
data.head()

x1        x2        x3          y
0  2.173282  2.350076  2.415250  35.708201
1  5.555118  5.993455  3.045520  60.201730
2  4.799505  3.901152  4.451028  56.969898
3  2.581442  5.075955  4.103971  54.576365
4  1.241630  4.261207  4.567827  50.139696

In [0]:
X = data.values

In [5]:
X

array([[ 2.17328187,  2.35007567,  2.41524966, 35.70820074],
       [ 5.55511808,  5.99345518,  3.04552049, 60.20172986],
       [ 4.79950491,  3.90115183,  4.45102767, 56.96989775],
       ...,
       [ 1.64510427,  4.50235896,  5.92562784, 58.20880789],
       [ 1.27479419,  3.86316655,  1.28767294, 33.4567469 ],
       [ 1.55295957,  2.34954563,  5.61161171, 49.0644137 ]])

In [0]:
X = X[:,:-1]

In [7]:
X

array([[2.17328187, 2.35007567, 2.41524966],
       [5.55511808, 5.99345518, 3.04552049],
       [4.79950491, 3.90115183, 4.45102767],
       ...,
       [1.64510427, 4.50235896, 5.92562784],
       [1.27479419, 3.86316655, 1.28767294],
       [1.55295957, 2.34954563, 5.61161171]])

In [8]:
X[:5]

array([[2.17328187, 2.35007567, 2.41524966],
       [5.55511808, 5.99345518, 3.04552049],
       [4.79950491, 3.90115183, 4.45102767],
       [2.58144234, 5.07595546, 4.10397118],
       [1.24162955, 4.26120663, 4.56782675]])

In [0]:
Y = data.values[:,-1]

In [10]:
Y[:5]

array([35.70820074, 60.20172986, 56.96989775, 54.5763646 , 50.13969565])

In [0]:
ones = np.array([1]*X.shape[0]).reshape((X.shape[0],1))

In [12]:
ones[:5]

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [0]:
X = np.concatenate((ones,X),axis=1)

In [14]:
X[:5]

array([[1.        , 2.17328187, 2.35007567, 2.41524966],
       [1.        , 5.55511808, 5.99345518, 3.04552049],
       [1.        , 4.79950491, 3.90115183, 4.45102767],
       [1.        , 2.58144234, 5.07595546, 4.10397118],
       [1.        , 1.24162955, 4.26120663, 4.56782675]])

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,random_state=42)

In [0]:
p_inv = np.linalg.inv(np.dot(X_train.T,X_train))

In [0]:
p_inv = np.dot(p_inv,X_train.T)

In [0]:
theta = np.dot(p_inv,y_train)

In [19]:
theta

array([10.53514277,  2.4878038 ,  3.59803286,  4.69658085])

In [0]:
y_pred = np.dot(theta,X_test.T)

In [21]:
y_pred[:5]

array([37.78536846, 56.54835523, 62.74306459, 39.36121846, 43.40236314])

In [22]:
y_test[:5]

array([37.65496625, 56.98158042, 62.8569962 , 38.94856476, 43.19129718])

In [0]:
from sklearn.metrics import mean_squared_error,r2_score

In [24]:
print("Mean squared error",mean_squared_error(y_test,y_pred))

Mean squared error 0.0904870332846944


In [25]:
print("r2 score ",r2_score(y_test,y_pred))

r2 score  0.9989336348393452
